# Etapa 1: Build da aplicação
FROM maven:3.9.5-eclipse-temurin-17 AS builder
  
  # Diretório de trabalho no contêiner de build
WORKDIR /app
  
  # Copie os arquivos de configuração do Maven e código-fonte
COPY pom.xml ./
COPY src ./src
  
  # Execute o comando de build para gerar o JAR
RUN mvn clean package -DskipTests
  
  # Etapa 2: Runtime (Execução da aplicação)
FROM eclipse-temurin:17-jre
  
  # Diretório de trabalho no contêiner final
WORKDIR /app
  
  # Baixe o Datadog Java Agent
RUN wget -O dd-java-agent.jar 'https://dtdg.co/latest-java-tracer'
  
  # Copie o JAR gerado na etapa de build para o contêiner final
COPY --from=builder /app/target/*.jar app.jar
  
  # Variáveis de ambiente para configurar o Datadog Agent
ENV DD_AGENT_HOST=datadog-agent
ENV DD_TRACE_AGENT_PORT=8126
ENV JAVA_OPTS="-javaagent:/app/dd-java-agent.jar"
  
  # Porta que a aplicação expõe (caso ela use alguma porta específica)
EXPOSE 8080
  
  # Comando para rodar a aplicação com o Datadog Java Agent
CMD ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
